export const USER = [
	{
	  _id: '1',
	  username: 'billgates',
	  firstName: 'Bill',
	  lastName: 'Gates',
	  email: 'billgates@example.com',
	  password: 'password123',
	  mobile: '1234567890',
	  profileImg: '/profile/user1.jpeg',
	  coverImg: '/cover/user1.jpeg',
	  pronouns: 'He/Him',
	  gender: 'Male',
	  type: 'Professional',
	  professional: {
		workExperience: 'Chair at Gates Foundation',
		currentSector: 'Non-profit',
		designation: 'Chair',
		lookingForCareerChange: false,
		organisation: 'Gates Foundation',
	  },
	  location: 'Seattle, Washington, United States',
	  dob: '1955-10-28',
	  bio: 'Chair, Gates Foundation and Founder, Breakthrough Energy',
	  skills: ['Leadership', 'Philanthropy', 'Business'],
	  education: 
		{
		  qualification: 'Bachelor',
		  degree: 'BA',
		  degreeType: 'Undergraduate',
		  specialization: 'Computer Science',
		  duration: {
			start: '1973',
			end: '1975',
		  },
		  institute: 'Harvard University',
		  skills: ['Software Development'],
		  location: 'Cambridge, MA',
		},
	  connections: 5000,
	  following: 300,
	  followers: 10000,
	  searchAppearance: 2000,
	  savedItems: [],
	},
	{
	  _id: '2',
	  username: 'sundarpichai',
	  firstName: 'Sundar',
	  lastName: 'Pichai',
	  email: 'sundar@example.com',
	  password: 'password123',
	  mobile: '0987654321',
	  profileImg: '/profile/user2.jpeg',
	  coverImg: '/cover/user2.jpeg',
	  pronouns: 'He/Him/His',
	  gender: 'Male',
	  type: 'Professional',
	  professional: {
		workExperience: 'CEO at Google',
		currentSector: 'Technology',
		designation: 'CEO',
		lookingForCareerChange: false,
		organisation: 'Google',
	  },
	  location: 'Mountain View, California, United States',
	  dob: '1972-06-10',
	  bio: 'CEO at Google',
	  skills: ['Leadership', 'Innovation', 'Business Strategy'],
	  education: [
		{
		  qualification: 'Master',
		  degree: 'MBA',
		  degreeType: 'Graduate',
		  specialization: 'Business Administration',
		  duration: {
			start: '1997',
			end: '1999',
		  },
		  institute: 'Stanford University',
		  skills: ['Business Strategy'],
		  location: 'Stanford, CA',
		},
	  ],
	  connections: 4500,
	  following: 400,
	  followers: 9500,
	  searchAppearance: 1800,
	  savedItems: [],
	},
	{
	  _id: '3',
	  username: 'shradhakhapra',
	  firstName: 'Shradha',
	  lastName: 'Khapra',
	  email: 'shradha@example.com',
	  password: 'password123',
	  mobile: '9876543210',
	  profileImg: '/profile/user3.jpeg',
	  coverImg: '/cover/user3.jpeg',
	  pronouns: 'She/Her',
	  gender: 'Female',
	  type: 'Professional',
	  professional: {
		workExperience: 'Co-founder at Apna College',
		currentSector: 'Education',
		designation: 'Co-founder',
		lookingForCareerChange: false,
		organisation: 'Apna College',
	  },
	  location: 'Delhi, India',
	  dob: '1995-04-15',
	  bio: 'Co-founder, Apna College | Ex-SDE Microsoft | 6Million+ YT | Google SPS’20',
	  skills: ['Software Development', 'YouTube Content', 'Teaching'],
	  education: [
		{
		  qualification: 'Bachelor',
		  degree: 'BTech',
		  degreeType: 'Undergraduate',
		  specialization: 'Computer Science',
		  duration: {
			start: '2013',
			end: '2017',
		  },
		  institute: 'Delhi Technological University',
		  skills: ['Programming', 'Algorithms'],
		  location: 'Delhi, India',
		},
	  ],
	  connections: 3000,
	  following: 700,
	  followers: 9000000,
	  searchAppearance: 5000,
	  savedItems: [],
	},
	{
	  _id: '4',
	  username: 'sandeepjain',
	  firstName: 'Sandeep',
	  lastName: 'Jain',
	  email: 'sandeep@example.com',
	  password: 'password123',
	  mobile: '9876541230',
	  profileImg: '/profile/user4.jpeg',
	  coverImg: '/cover/user4.jpeg',
	  pronouns: 'He/Him/His',
	  gender: 'Male',
	  type: 'Professional',
	  professional: {
		workExperience: 'Founder & CEO at GeeksforGeeks',
		currentSector: 'Education',
		designation: 'Founder & CEO',
		lookingForCareerChange: false,
		organisation: 'GeeksforGeeks',
	  },
	  location: 'Noida, Uttar Pradesh, India',
	  dob: '1980-08-05',
	  bio: 'Founder & CEO at GeeksforGeeks',
	  skills: ['Programming', 'Leadership', 'Entrepreneurship'],
	  education: [
		{
		  qualification: 'Bachelor',
		  degree: 'BTech',
		  degreeType: 'Undergraduate',
		  specialization: 'Computer Science',
		  duration: {
			start: '1998',
			end: '2002',
		  },
		  institute: 'IIT Roorkee',
		  skills: ['Programming', 'Algorithms'],
		  location: 'Roorkee, India',
		},
	  ],
	  connections: 4500,
	  following: 400,
	  followers: 5000,
	  searchAppearance: 1200,
	  savedItems: [],
	},
	{
	  _id: '5',
	  username: 'yashgarg',
	  firstName: 'Yash',
	  lastName: 'Garg',
	  email: 'yash@example.com',
	  password: 'password123',
	  mobile: '9876543212',
	  profileImg: '/profile/user5.jpeg',
	  coverImg: '/cover/user5.jpeg',
	  pronouns: 'He/Him/His',
	  gender: 'Male',
	  type: 'Professional',
	  professional: {
		workExperience: 'Founder at College Setu',
		currentSector: 'Education',
		designation: 'Founder',
		lookingForCareerChange: false,
		organisation: 'College Setu',
	  },
	  location: 'Delhi, India',
	  dob: '1990-05-05',
	  bio: 'Founder, College Setu | 10 Million YouTube views | We’re Hiring',
	  skills: ['Entrepreneurship', 'Digital Marketing', 'Content Creation'],
	  education: [
		{
		  qualification: 'Bachelor',
		  degree: 'BTech',
		  degreeType: 'Undergraduate',
		  specialization: 'Engineering',
		  duration: {
			start: '2008',
			end: '2012',
		  },
		  institute: 'Delhi University',
		  skills: ['Digital Marketing'],
		  location: 'Delhi, India',
		},
	  ],
	  connections: 6000,
	  following: 500,
	  followers: 12000,
	  searchAppearance: 2100,
	  savedItems: [],
	},
	{
	  _id: '6',
	  username: 'ajayraj',
	  firstName: 'Ajay',
	  lastName: 'Raj',
	  email: 'ajay@example.com',
	  password: 'password123',
	  mobile: '9876545678',
	  profileImg: '/profile/user6.jpeg',
	  coverImg: '/cover/user6.jpeg',
	  pronouns: 'He/Him/His',
	  gender: 'Male',
	  type: 'Professional',
	  professional: {
		workExperience: 'Software Engineer at Paytm',
		currentSector: 'Technology',
		designation: 'Software Engineer',
		lookingForCareerChange: false,
		organisation: 'Paytm',
	  },
	  location: 'Delhi, India',
	  dob: '1995-03-22',
	  bio: 'Software Engineer at Paytm',
	  skills: ['Programming', 'Mobile Development', 'Problem Solving'],
	  education: [
		{
		  qualification: 'Bachelor',
		  degree: 'BTech',
		  degreeType: 'Undergraduate',
		  specialization: 'Computer Science',
		  duration: {
			start: '2013',
			end: '2017',
		  },
		  institute: 'Delhi Technological University',
		  skills: ['Programming', 'Web Development'],
		  location: 'Delhi, India',
		},
	  ],
	  connections: 3500,
	  following: 500,
	  followers: 4000,
	  searchAppearance: 1500,
	  savedItems: [],
	},
	{
		_id: '10',
		username: 'saymahtab',
		firstName: 'Mohd',
		lastName: 'Mahtab',
		email: 'reachmahtabsce@gmail.com',
		password: 'password123',
		mobile: '1234567890',
		profileImg: '/user.png',
		coverImg: '/cover/user1.jpeg',
		pronouns: 'He/Him',
		gender: 'Male',
		type: 'Professional',
		professional: {
		  workExperience: 'Chair at Gates Foundation',
		  currentSector: 'Non-profit',
		  designation: 'Chair',
		  lookingForCareerChange: false,
		  organisation: 'Gates Foundation',
		},
		location: 'Himachal Pradesh, India',
		dob: '1955-10-28',
		bio: 'Mern Stack Developer | React.js, Node.js, Express.js, Tailwindcss, MongoDB | 250+ Problems Leet code',
		skills: ['Leadership', 'Philanthropy', 'Business'],
		education: 
		  {
			qualification: 'Bachelor',
			degree: 'BA',
			degreeType: 'Undergraduate',
			specialization: 'Computer Science',
			duration: {
			  start: '1973',
			  end: '1975',
			},
			institute: 'Shivalik college of Engineering, Dehradun',
			skills: ['Software Development'],
			location: 'Cambridge, MA',
		  },
		connections: 5000,
		following: 300,
		followers: 10000,
		searchAppearance: 2000,
		savedItems: [],
	  },
]


export const POSTS = [
	{
		_id: "1",
		text: "In London this week, I had the opportunity to speak with UK MPs about the country’s vital role in tackling global health challenges at an event hosted by",
		img: "/posts/post5.png",
		user: {
			_id: '4',
			username: 'sandeepjain',
			firstName: 'Sandeep',
			lastName: 'Jain',
			profileImg: '/profile/user4.jpeg',
			coverImg: '/cover/user4.jpeg',
			gender: 'Male',
			type: 'Professional',
			location: 'Noida, Uttar Pradesh, India',
			dob: '1980-08-05',
			bio: 'Founder & CEO at GeeksforGeeks',
			skills: ['Programming', 'Leadership', 'Entrepreneurship'],
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			{
				_id:"1",
				user: {
					username: "Guddu Kumar",
					profileImg: "/avatars/girl1.png",
					fullName: "Guddu Kumar",
				},
			},
			{
				_id:"3",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
			{
				_id:"4",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
			{
				_id:"5",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			}
		],
	},
	{
		_id: "2",
		text: "For my first-ever LinkedIn post, I thought Id share a sneak peek of the Shoreline Amphitheatre stage, as we put some finishing touches on our keynote for Google I/O tomorrow. Cant wait to see those seats filled with developers from around the world who are building the next generation of AI experiences. Excited to join Demis Hassabis Elizabeth Reid Sissie H. James Manyika",
		img: "/posts/post1.jpeg",
		user: {
			_id: '1',
			username: 'billgates',
			firstName: 'Bill',
			lastName: 'Gates',
			email: 'billgates@example.com',
			profileImg: '/profile/user1.jpeg',
			coverImg: '/cover/user1.jpeg',
			gender: 'Male',
			type: 'Professional',
			location: 'Seattle, Washington, United States',
			dob: '1955-10-28',
			bio: 'Chair, Gates Foundation and Founder, Breakthrough Energy',
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			{
				_id:"1",
				user: {
					username: "Guddu Kumar",
					profileImg: "/avatars/girl1.png",
					fullName: "Guddu Kumar",
				},
			},
			{
				_id:"3",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
			{
				_id:"4",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
			{
				_id:"5",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			}
		],
	},
	{
		_id: "3",
		text: "Earlier this week, I had a great conversation with Doug McMillon during a visit with Walmart's global technology team. We covered everything from the potential of generative AI and how Walmart is using our Gemini models to improve discoverability on their site... ",
		img: "/posts/post3.jpeg",
		user: {
			_id: '2',
			username: 'sundarpichai',
			firstName: 'Sundar',
			lastName: 'Pichai',
			email: 'sundar@example.com',
			password: 'password123',
			mobile: '0987654321',
			profileImg: '/profile/user2.jpeg',
			coverImg: '/cover/user2.jpeg',
			pronouns: 'He/Him/His',
			gender: 'Male',
			type: 'Professional',
			professional: {
				workExperience: 'CEO at Google',
				currentSector: 'Technology',
				designation: 'CEO',
				lookingForCareerChange: false,
				organisation: 'Google',
			},
			location: 'Mountain View, California, United States',
			dob: '1972-06-10',
			bio: 'CEO at Google',
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			{
				_id:"1",
				user: {
					username: "Guddu Kumar",
					profileImg: "/avatars/girl1.png",
					fullName: "Guddu Kumar",
				},
			},
			{
				_id:"3",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
			{
				_id:"4",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
			{
				_id:"5",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			}
		],
	},
	{
		_id: "4",
		text: "Thrilled to announce that I’ve successfully completed the MERN stack course at Explorin Academy, Roorkee! This journey has been one of the most rewarding experiences of my life, filled with hard work, growth, and unforgettable moments.",
		img: "/posts/C1.jpeg",
		user: {
			_id: '5',
			username: 'yashgarg',
			firstName: 'Yash',
			lastName: 'Garg',
			email: 'yash@example.com',
			password: 'password123',
			mobile: '9876543212',
			profileImg: '/profile/user5.jpeg',
			coverImg: '/cover/user5.jpeg',
			pronouns: 'He/Him/His',
			gender: 'Male',
			type: 'Professional',
			professional: {
				workExperience: 'Founder at College Setu',
				currentSector: 'Education',
				designation: 'Founder',
				lookingForCareerChange: false,
				organisation: 'College Setu',
			},
			location: 'Delhi, India',
			dob: '1990-05-05',
			bio: 'Founder, College Setu | 10 Mill'
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			{
				_id:"1",
				user: {
					username: "Guddu Kumar",
					profileImg: "/avatars/girl1.png",
					fullName: "Guddu Kumar",
				},
			},
			{
				_id:"3",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
			{
				_id:"4",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
			{
				_id:"5",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			}
		],
	},
	{
		_id: "5",
		text: "Thrilled to announce that I ve successfully completed the MERN stack course at Explorin Academy, Roorkee! This journey has been one of the most rewarding experiences of my life, filled with hard work, growth, and unforgettable moments.",
		img: "/posts/post4.jpeg",
		user: {
			_id: '3',
			username: 'shradhakhapra',
			firstName: 'Shradha',
			lastName: 'Khapra',
			email: 'shradha@example.com',
			password: 'password123',
			mobile: '9876543210',
			profileImg: '/profile/user3.jpeg',
			coverImg: '/cover/user3.jpeg',
			pronouns: 'She/Her',
			gender: 'Female',
			type: 'Professional',
			professional: {
				workExperience: 'Co-founder at Apna College',
				currentSector: 'Education',
				designation: 'Co-founder',
				lookingForCareerChange: false,
				organisation: 'Apna College',
			},
			location: 'Delhi, India',
			dob: '1995-04-15',
			bio: 'Co-founder, Apna College | Ex-SDE Microsoft | 6Million+ YT | Google SPS’20',
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			{
				_id:"1",
				user: {
					username: "Guddu Kumar",
					profileImg: "/avatars/girl1.png",
					fullName: "Guddu Kumar",
				},
			},
			{
				_id:"3",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
			{
				_id:"4",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			},
			{
				_id:"5",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl1.png",
					fullName: "Jane Doe",
				},
			}
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "John Doe",
		username: "johndoe",
		profileImg: "/avatars/boy2.png",
	},
	{
		_id: "2",
		fullName: "Jane Doe",
		username: "janedoe",
		profileImg: "/avatars/girl1.png",
	},
	{
		_id: "3",
		fullName: "Bob Doe",
		username: "bobdoe",
		profileImg: "/avatars/boy3.png",
	},
	{
		_id: "4",
		fullName: "Daisy Doe",
		username: "daisydoe",
		profileImg: "/avatars/girl2.png",
	},
];