export const mentors = [
    {
      user: "64895cf345e3a97d6b49f1a1", // Example ObjectId for user reference
      profile: {
        profileImg: "/profile/user1.jpeg",
        banner: "https://example.com/banners/business.jpg",
        username: "businessguru",
        firstName: "Alice",
        lastName: "Johnson",
        gender: "Female",
        currentOrganization: "McKinsey & Company",
        organizationLogo: "https://example.com/logos/mckinsey.png",
        industry: "Business Consulting",
        currentRole: "Senior Consultant",
        totalExperience: 10,
        shortHeading: "Empowering business leaders to achieve more.",
        bio: "I specialize in business strategy and leadership development with 10 years of experience in top consulting firms.",
        languages: ["English", "French"],
        socialLinks: {
          linkedIn: "https://linkedin.com/in/alicejohnson",
          twitter: "https://twitter.com/alicejohnson",
        },
      },
      expertise: {
        domain: ["Business and Management"],
        topics: ["Business Strategy", "Leadership Development", "Consulting"],
        skills: ["Agile", "Business Development", "Career Coaching", "Consulting"],
      },
      experience: [
        {
          designation: "Senior Consultant",
          sector: "Business Consulting",
          employmentType: "Full-time",
          organization: "McKinsey & Company",
          isCurrent: true,
          from: new Date("2018-01-01"),
          location: { country: "USA", state: "New York", city: "New York City" },
        },
      ],
      education: [
        {
          qualification: "MBA",
          degree: "Master of Business Administration",
          from: new Date("2015-08-01"),
          to: new Date("2017-05-01"),
          specialization: "Strategy",
          university: "Harvard Business School",
          location: { country: "USA", state: "Massachusetts", city: "Cambridge" },
        },
      ],
      services: [
        { name: "Quick Call", description: "30 Min quick call", duration: "30 Min", price: 500 },
        { name: "1:1 Mentorship", description: "60 Min personalized session", duration: "60 Min", price: 1000 },
      ],
      availability: [
        { day: "Monday", isActive: true, slots: ["10:00 AM - 12:00 PM", "3:00 PM - 5:00 PM"] },
        { day: "Wednesday", isActive: true, slots: ["9:00 AM - 11:00 AM"] },
      ],
      payments: [
        {
          mentee: "64895cf345e3a97d6b49f1a2",
          status: "received",
          platformFee: 50,
          paymentAmount: 500,
          price: 450,
        },
      ],
      reviews: [
        { menteeName: "John Doe", message: "Great insights into business strategy!", rating: 5 },
        { menteeName: "John Doe", message: "Great insights into business strategy!", rating: 5 },
        { menteeName: "John Doe", message: "Great insights into business strategy!", rating: 5 },
      ],
      totalSessions: 20,
      totalDuration: 600,
      totalReviews: 5,
      avgRating: 4.8,
    },
    {
      user: "64895cf345e3a97d6b49f1a3",
      profile: {
        profileImg: "https://example.com/profiles/mentor2.jpg",
        banner: "https://example.com/banners/engineering.jpg",
        username: "techwhiz",
        firstName: "Bob",
        lastName: "Smith",
        gender: "Male",
        currentOrganization: "Google",
        organizationLogo: "https://example.com/logos/google.png",
        industry: "Software Engineering",
        currentRole: "Senior Software Engineer",
        totalExperience: 8,
        shortHeading: "Helping engineers excel in tech.",
        bio: "Experienced in software engineering with a focus on cloud computing and AI technologies.",
        languages: ["English", "Spanish"],
        socialLinks: {
          linkedIn: "https://linkedin.com/in/bobsmith",
        },
      },
      expertise: {
        domain: ["Engineering & Technology & Data"],
        topics: ["Algorithms", "Data Structures", "Cloud Computing", "AI"],
        skills: ["Algorithms", "AWS", "Cloud", "Data Science", "Python"],
      },
      experience: [
        {
          designation: "Senior Software Engineer",
          sector: "Technology",
          employmentType: "Full-time",
          organization: "Google",
          isCurrent: true,
          from: new Date("2017-04-01"),
          location: { country: "USA", state: "California", city: "Mountain View" },
        },
      ],
      education: [
        {
          qualification: "BSc",
          degree: "Computer Science",
          from: new Date("2008-09-01"),
          to: new Date("2012-06-01"),
          university: "Stanford University",
          location: { country: "USA", state: "California", city: "Stanford" },
        },
      ],
      services: [
        { name: "Mock Interview", description: "45 Min mock technical interview", duration: "45 Min", price: 700 },
        { name: "Project Guidance", description: "Detailed project feedback and advice", duration: "60 Min", price: 1200 },
      ],
      availability: [
        { day: "Tuesday", isActive: true, slots: ["2:00 PM - 4:00 PM"] },
        { day: "Thursday", isActive: true, slots: ["10:00 AM - 12:00 PM"] },
      ],
      payments: [
        {
          mentee: "64895cf345e3a97d6b49f1a4",
          status: "pending",
          platformFee: 100,
          paymentAmount: 1200,
          price: 1100,
        },
      ],
      reviews: [
        { menteeName: "Alice Wong", message: "Fantastic support in tech skills.", rating: 5 },
        { menteeName: "Chris Lee", message: "Very knowledgeable!", rating: 4 },
      ],
      totalSessions: 15,
      totalDuration: 675,
      totalReviews: 7,
      avgRating: 4.6,
    },
    {
      user: "64895cf345e3a97d6b49f1a5",
      profile: {
        profileImg: "https://example.com/profiles/mentor3.jpg",
        banner: "https://example.com/banners/design.jpg",
        username: "designpro",
        firstName: "Charlie",
        lastName: "Brown",
        gender: "Non-binary",
        currentOrganization: "Apple",
        organizationLogo: "https://example.com/logos/apple.png",
        industry: "Product Design",
        currentRole: "Lead Product Designer",
        totalExperience: 6,
        shortHeading: "Designing impactful products with creativity.",
        bio: "I bring a wealth of experience in user-centered design, with a special focus on usability and aesthetics.",
        languages: ["English", "German"],
        socialLinks: {
          linkedIn: "https://linkedin.com/in/charliebrown",
          twitter: "https://twitter.com/designpro",
        },
      },
      expertise: {
        domain: ["Product Design"],
        topics: ["UI/UX Design", "Interaction Design", "Prototyping", "Design Thinking"],
        skills: ["Figma", "Interaction Design", "UI/UX", "Product Strategy", "Sketch"],
      },
      experience: [
        {
          designation: "Lead Product Designer",
          sector: "Product Design",
          employmentType: "Full-time",
          organization: "Apple",
          isCurrent: true,
          from: new Date("2019-02-01"),
          location: { country: "USA", state: "California", city: "Cupertino" },
        },
      ],
      education: [
        {
          qualification: "MDes",
          degree: "Master of Design",
          from: new Date("2014-08-01"),
          to: new Date("2016-05-01"),
          specialization: "User Experience",
          university: "Rhode Island School of Design",
          location: { country: "USA", state: "Rhode Island", city: "Providence" },
        },
      ],
      services: [
        { name: "Portfolio Review", description: "Detailed feedback on design portfolio", duration: "45 Min", price: 800 },
        { name: "Design Consultation", description: "1 hour consultation on product design", duration: "60 Min", price: 1500 },
      ],
      availability: [
        { day: "Monday", isActive: true, slots: ["11:00 AM - 1:00 PM", "3:00 PM - 5:00 PM"] },
        { day: "Friday", isActive: true, slots: ["9:00 AM - 12:00 PM"] },
      ],
      payments: [
        {
          mentee: "64895cf345e3a97d6b49f1a6",
          status: "received",
          platformFee: 75,
          paymentAmount: 800,
          price: 725,
        },
      ],
      reviews: [
        { menteeName: "Sarah King", message: "Great help with my UX design project.", rating: 5 },
      ],
      totalSessions: 10,
      totalDuration: 450,
      totalReviews: 4,
      avgRating: 5,
    },
    {
        user: "64895cf345e3a97d6b49f1a7", // Example ObjectId for user reference
        profile: {
          profileImg: "https://example.com/profiles/mentor4.jpg",
          banner: "https://example.com/banners/data-science.jpg",
          username: "datascientist",
          firstName: "Sophia",
          lastName: "Martinez",
          gender: "Female",
          currentOrganization: "Amazon Web Services",
          organizationLogo: "https://example.com/logos/aws.png",
          industry: "Cloud Computing & Data Science",
          currentRole: "Principal Data Scientist",
          totalExperience: 12,
          shortHeading: "Transforming data into valuable insights.",
          bio: "I work at the intersection of AI and cloud computing, providing data-driven solutions for business transformation.",
          languages: ["English", "Spanish"],
          socialLinks: {
            linkedIn: "https://linkedin.com/in/sophiamartinez",
          },
        },
        expertise: {
          domain: ["Engineering & Technology & Data"],
          topics: ["Data Science", "Machine Learning", "Cloud Computing", "Data Analytics"],
          skills: ["Python", "R", "Machine Learning", "AWS", "Big Data", "Deep Learning"],
        },
        experience: [
          {
            designation: "Principal Data Scientist",
            sector: "Cloud Computing",
            employmentType: "Full-time",
            organization: "Amazon Web Services",
            isCurrent: true,
            from: new Date("2016-03-01"),
            location: { country: "USA", state: "Washington", city: "Seattle" },
          },
        ],
        education: [
          {
            qualification: "PhD",
            degree: "Data Science",
            from: new Date("2010-09-01"),
            to: new Date("2014-06-01"),
            university: "Massachusetts Institute of Technology",
            location: { country: "USA", state: "Massachusetts", city: "Cambridge" },
          },
        ],
        services: [
          { name: "ML Model Review", description: "Review and optimize your machine learning models", duration: "60 Min", price: 1200 },
          { name: "Data Science Consultation", description: "Guidance on setting up data pipelines and analytics", duration: "90 Min", price: 1500 },
        ],
        availability: [
          { day: "Monday", isActive: true, slots: ["1:00 PM - 3:00 PM"] },
          { day: "Wednesday", isActive: true, slots: ["9:00 AM - 11:00 AM"] },
        ],
        payments: [
          {
            mentee: "64895cf345e3a97d6b49f1a8",
            status: "pending",
            platformFee: 150,
            paymentAmount: 1200,
            price: 1050,
          },
        ],
        reviews: [
          { menteeName: "John Carter", message: "Sophia's insights into data science were incredible!", rating: 5 },
        ],
        totalSessions: 18,
        totalDuration: 720,
        totalReviews: 6,
        avgRating: 4.9,
      },
      {
        user: "64895cf345e3a97d6b49f1a9", 
        profile: {
          profileImg: "https://example.com/profiles/mentor5.jpg",
          banner: "https://example.com/banners/product-design.jpg",
          username: "uxexpert",
          firstName: "David",
          lastName: "Lewis",
          gender: "Male",
          currentOrganization: "Spotify",
          organizationLogo: "https://example.com/logos/spotify.png",
          industry: "Product Design & UX",
          currentRole: "Senior UX Designer",
          totalExperience: 7,
          shortHeading: "Crafting seamless user experiences with empathy.",
          bio: "As a UX designer, I focus on user-centered design principles to create engaging, intuitive, and accessible products.",
          languages: ["English", "Italian"],
          socialLinks: {
            linkedIn: "https://linkedin.com/in/davidlewis",
            twitter: "https://twitter.com/uxexpert",
          },
        },
        expertise: {
          domain: ["Product Design"],
          topics: ["UX/UI Design", "Interaction Design", "Prototyping", "User Research"],
          skills: ["Figma", "Wireframing", "User Testing", "UI/UX Design", "Prototyping", "Usability Testing"],
        },
        experience: [
          {
            designation: "Senior UX Designer",
            sector: "Technology",
            employmentType: "Full-time",
            organization: "Spotify",
            isCurrent: true,
            from: new Date("2018-06-01"),
            location: { country: "USA", state: "New York", city: "New York City" },
          },
        ],
        education: [
          {
            qualification: "BA",
            degree: "Graphic Design",
            from: new Date("2010-08-01"),
            to: new Date("2014-05-01"),
            university: "Parsons School of Design",
            location: { country: "USA", state: "New York", city: "New York City" },
          },
        ],
        services: [
          { name: "UX/UI Review", description: "Review and improve your product's user experience", duration: "45 Min", price: 900 },
          { name: "Design Sprint", description: "Lead a design sprint to solve your product's challenges", duration: "2 Hours", price: 1800 },
        ],
        availability: [
          { day: "Tuesday", isActive: true, slots: ["10:00 AM - 12:00 PM"] },
          { day: "Thursday", isActive: true, slots: ["2:00 PM - 4:00 PM"] },
        ],
        payments: [
          {
            mentee: "64895cf345e3a97d6b49f1aa",
            status: "received",
            platformFee: 90,
            paymentAmount: 900,
            price: 810,
          },
        ],
        reviews: [
          { menteeName: "Emma Green", message: "David helped me fine-tune the design for my app, really insightful.", rating: 5 },
        ],
        totalSessions: 12,
        totalDuration: 540,
        totalReviews: 4,
        avgRating: 4.8,
      },
      {
        user: "64895cf345e3a97d6b49f1ab", 
        profile: {
          profileImg: "https://example.com/profiles/mentor6.jpg",
          banner: "https://example.com/banners/finance.jpg",
          username: "fincoach",
          firstName: "Ethan",
          lastName: "Davies",
          gender: "Male",
          currentOrganization: "Goldman Sachs",
          organizationLogo: "https://example.com/logos/goldman-sachs.png",
          industry: "Finance",
          currentRole: "Financial Advisor",
          totalExperience: 15,
          shortHeading: "Helping individuals grow their wealth and financial literacy.",
          bio: "As a financial advisor, I guide my clients towards smart investment strategies and financial planning.",
          languages: ["English", "French"],
          socialLinks: {
            linkedIn: "https://linkedin.com/in/ethandavies",
          },
        },
        expertise: {
          domain: ["Business and Management"],
          topics: ["Investment Strategies", "Personal Finance", "Wealth Management", "Financial Planning"],
          skills: ["Financial Planning", "Investment Strategies", "Risk Management", "Stock Market", "Retirement Planning"],
        },
        experience: [
          {
            designation: "Financial Advisor",
            sector: "Finance",
            employmentType: "Full-time",
            organization: "Goldman Sachs",
            isCurrent: true,
            from: new Date("2013-01-01"),
            location: { country: "USA", state: "New York", city: "New York City" },
          },
        ],
        education: [
          {
            qualification: "MBA",
            degree: "Finance",
            from: new Date("2007-08-01"),
            to: new Date("2009-06-01"),
            university: "Wharton School of the University of Pennsylvania",
            location: { country: "USA", state: "Pennsylvania", city: "Philadelphia" },
          },
        ],
        services: [
          { name: "Financial Planning", description: "60 Min financial planning session", duration: "60 Min", price: 1100 },
          { name: "Investment Portfolio Review", description: "Review and optimize your investment portfolio", duration: "45 Min", price: 850 },
        ],
        availability: [
          { day: "Monday", isActive: true, slots: ["9:00 AM - 11:00 AM"] },
          { day: "Friday", isActive: true, slots: ["1:00 PM - 3:00 PM"] },
        ],
        payments: [
          {
            mentee: "64895cf345e3a97d6b49f1ac",
            status: "received",
            platformFee: 100,
            paymentAmount: 1100,
            price: 1000,
          },
        ],
        reviews: [
          { menteeName: "Lucas White", message: "Ethan gave me great advice on planning for retirement.", rating: 5 },
        ],
        totalSessions: 20,
        totalDuration: 960,
        totalReviews: 7,
        avgRating: 4.7,
      },
  ];
  